PJA/src/main/java/com/project/PJA/security/config/RedisConfig.java

5
Redis 설정 추가
- [✓ ] 빌드 설정, 패키지 관리 등 기타 작업
- [ ✓] 코드에 영향을 주지 않는 변경사항

feat: Redis 설정 추가

---

PJA/src/main/java/com/project/PJA/exception/BadRequestException.java
PJA/src/main/java/com/project/PJA/exception/ErrorResponse.java
PJA/src/main/java/com/project/PJA/exception/ForbiddenException.java
PJA/src/main/java/com/project/PJA/exception/GlobalExceptionHandler.java
PJA/src/main/java/com/project/PJA/exception/NotFoundException.java
PJA/src/main/java/com/project/PJA/exception/ServiceUnavailableException.java
PJA/src/main/java/com/project/PJA/exception/UnauthorizedException.java

closed #13
전역 예외 처리 기능을 추가하여 일관된 에러 응답 형식을 제공합니다.
클라이언트가 에러 상황을 쉽게 처리할 수 있도록 ErrorResponse 객체로 메시지를 통일했습니다.
- 전역 예외 처리 클래스(GlobalExceptionHandler) 추가
- 공통 에러 응답 객체(ErrorResponse) 정의
- 400, 401, 403, 404, 500, 503 예외 핸들러 구현
- 커스텀 예외 클래스(BadRequestException 등) 추가

[Feat] 전역 예외 처리 기능 구현 및 에러 응답 통일

---

PJA/src/main/java/com/project/PJA/common/dto/ErrorResponse.java
PJA/src/main/java/com/project/PJA/common/dto/SuccessResponse.java
PJA/src/main/java/com/project/PJA/exception/GlobalExceptionHandler.java

closed #15 
공통 dto에 성공 응답 dto 생성, 실패 응답 dto 이동

[Feat] 공통 DTO 생성

---

PJA/src/main/java/com/project/PJA/common/dto/ErrorResponse.java
PJA/src/main/java/com/project/PJA/security/config/AuthManagerConfig.java
PJA/src/main/java/com/project/PJA/security/config/PasswordEncoderConfig.java
PJA/src/main/java/com/project/PJA/security/config/RedisConfig.java
PJA/src/main/java/com/project/PJA/security/config/SecurityConfig.java
PJA/src/main/java/com/project/PJA/security/controller/AuthController.java
PJA/src/main/java/com/project/PJA/security/dto/LoginDto.java
PJA/src/main/java/com/project/PJA/security/service/AuthUserService.java
PJA/src/main/java/com/project/PJA/security/service/CustomUserDetailService.java
PJA/src/main/java/com/project/PJA/user/controller/UserController.java
PJA/src/main/java/com/project/PJA/user/dto/SignupDto.java
PJA/src/main/java/com/project/PJA/user/entity/Users.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java
PJA/src/test/java/com/project/PJA/user/controller/UserControllerTest.java

[Feat & Fix] 회원가입 기능 구현 & 로그인 api 오류 수정

---

PJA/src/main/java/com/project/PJA/email/service/EmailService.java
PJA/src/main/java/com/project/PJA/email/service/EmailServiceImpl.java

closed #22 
- 이메일 발송 서비스 클래스 구현

[Feat] 사용자에게 이메일 전송 기능 구현

---

PJA/src/main/java/com/project/PJA/security/controller/AuthController.java
PJA/src/main/java/com/project/PJA/security/jwt/JwtAuthenticationFilter.java
PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
PJA/src/main/java/com/project/PJA/user/dto/ChangePwRequestDto.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

[Feat] 비밀번호 변경 기능 추가

---

PJA/src/main/java/com/project/PJA/email/service/EmailService.java
PJA/src/main/java/com/project/PJA/email/service/EmailServiceImpl.java
PJA/src/main/java/com/project/PJA/security/service/EmailVerificationService.java
PJA/src/main/java/com/project/PJA/user/controller/UserController.java
PJA/src/main/java/com/project/PJA/user/dto/ChangePw2RequestDto.java
PJA/src/main/java/com/project/PJA/user/dto/IdEmailRequestDto.java
PJA/src/main/java/com/project/PJA/user/dto/VerifyEmailRequestDto.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

- 비밀번호 찾기용 인증번호 이메일 전송 기능 구현
- 비밀번호 찾기용 인증번호 확인 기능 구현
- 이메일 인증 후 비밀번호 변경 기능 구현

[Feat] 이메일 인증 후 비밀번호 찾기(변경) 기능 추가

---

PJA/.gitignore
PJA/docker-compose.yml
PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
PJA/src/main/java/com/project/PJA/common/file/FileStorageService.java
PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

프로필 이미지 업데이트 기능 추가
프로필 이미지 삭제 기능 추가
프로필 이미지 조회 기능 추가

[Feat] 프로필 이미지 업데이트/삭제/조회 기능 추가

---

PJA/src/main/java/com/project/PJA/security/controller/AuthController.java
PJA/src/main/java/com/project/PJA/user/controller/UserController.java
PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

컨트롤러 반환 타입 수정
api url 변경 등....

[Refactor] 회원 관리 코드 전반 리팩토링

---

PJA/src/main/java/com/project/PJA/erd/controller/ErdColumnController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdRelationController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdTableController.java
PJA/src/main/java/com/project/PJA/erd/dto/CreateErdRelationDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/ERDFlowResponseDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/EdgeDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/FieldDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/TableNodeDto.java
PJA/src/main/java/com/project/PJA/erd/entity/ErdRelationships.java
PJA/src/main/java/com/project/PJA/erd/entity/ErdTable.java
PJA/src/main/java/com/project/PJA/erd/repository/ErdRelationshipsRepository.java
PJA/src/main/java/com/project/PJA/erd/service/ErdColumnService.java
PJA/src/main/java/com/project/PJA/erd/service/ErdRelationService.java
PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
PJA/src/main/java/com/project/PJA/erd/service/ErdTableService.java
PJA/src/main/java/com/project/PJA/erd/service/ReactFlowConverter.java

- ERD 생성 및 조회
- ERD 테이블 생성/수정/삭제
- ERD 컬럼 생성/수정/삭제
- ERD 관계 생성/삭제

[Feature] ERD, ERD 테이블, ERD 컬럼, ERD 관계 기능 추가

---

PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
PJA/src/main/java/com/project/PJA/api/dto/ApiRequest.java
PJA/src/main/java/com/project/PJA/api/dto/ApiResponse.java
PJA/src/main/java/com/project/PJA/api/dto/Data.java
PJA/src/main/java/com/project/PJA/api/dto/Response.java
PJA/src/main/java/com/project/PJA/api/entity/Api.java
PJA/src/main/java/com/project/PJA/api/repository/ApiRepository.java
PJA/src/main/java/com/project/PJA/api/service/ApiService.java

closed #46 
API 명세서 저장, 생성, 수정, 삭제 기능 생성

[Feat] API 명세서 기능 추가

---

PJA/src/main/java/com/project/PJA/security/controller/AuthController.java

[Fix] 쿠키에 secure설정 주석 처리 풀기

---

PJA/src/main/java/com/project/PJA/common/config/WebConfig.java

[Fix] cors 설정 관련 프론트 도메인 수정

---

PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
PJA/src/main/java/com/project/PJA/security/service/AuthUserService.java

refresh token 토큰 생성 시의 만료 기간 변경

[Fix] refresh token 토큰 생성 시의 만료 기간 변경

---

PJA/src/main/java/com/project/PJA/user/entity/Users.java

getUsername 반환값 잘못된거 수정(name 반환으로 수정)

[Fix] getUsername 반환값 잘못된거 수정

---

PJA/.gitignore
PJA/build.gradle
PJA/docker-compose.yml
PJA/logstash.conf
PJA/src/main/resources/logback.xml

[Chore] elastic search 환경 설정

---

PJA/.gitignore
PJA/build.gradle
PJA/docker-compose.yml
PJA/logstash.conf
PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceUpdateRequest.java
PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
PJA/src/main/resources/application.properties
PJA/src/main/resources/logback.xml

[Fix] JWT Secret Key 인코딩 방식 지정

---

PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
PJA/src/main/resources/application.properties

에러 로그 추가 및 jwt_secret key 설정 강화

[Fix] 에러 로그 추가 및 jwt_secret key 설정 강화

---

PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdColumnController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdRelationController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdTableController.java
PJA/src/main/java/com/project/PJA/idea/controller/IdeaController.java
PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
PJA/src/main/java/com/project/PJA/member/controller/MemberController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureCategoryController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java

closed #82 
- 아이디어 생성 시 status code를 200에서 201로 수정
- 아이디어 생성 성공 응답 메시지 수정
- 전체 URL 경로 중 workspace를 workspaces로 변경

[Chore] 자잘한 설정 변경

---

PJA/build.gradle
PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
PJA/src/main/java/com/project/PJA/projectinfo/dto/ProblemSolvingData.java
PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoCreateRequest.java
PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoCreateResponse.java
PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoData.java
PJA/src/main/java/com/project/PJA/projectinfo/dto/ProjectInfoWrapper.java
PJA/src/main/java/com/project/PJA/projectinfo/repository/ProjectInfoRepository.java
PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
PJA/src/main/java/com/project/PJA/requirement/dto/RequirementRecommendationRequest.java
PJA/src/main/java/com/project/PJA/requirement/dto/RequirementRecommendationResponse.java
PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteRequest.java
PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceInviteResponse.java

closed #72 
- 기존에는 오직 오너만 요청 가능했으나, 멤버도 요청 가능하도록 변경
- AI 요청 시 반환하는 DTO 구조를 수정
- AI 요청 시 프로젝트 정보를 반환하면서 동시에 DB에 저장하도록 변경

[Refactor] AI 요청 기능 개선 및 저장 로직 추가

---

PJA/src/main/java/com/project/PJA/user/entity/Users.java

[Fix] email nullable 설정

---

.github/workflows/deploy.yml

closed #90 
- main 브랜치 푸시 시 자동 빌드 및 배포 CI/CD 파이프라인 설정
- Gradle 빌드 (테스트 제외)
- AWS ECR 로그인 및 Docker 이미지 빌드, 푸시
- EC2 서버에 SSH 접속 후 Docker 컨테이너 재시작으로 배포 자동화
- GitHub Secrets를 활용해 .env, application-dev.properties 파일 생성

[Chore] CI/CD 설정

---

.github/workflows/deploy.yml

[Fix] Gradlew 실행 권한 설정

---

.github/workflows/deploy.yml
PJA/src/main/java/com/project/PJA/notification/controller/NotificationController.java
PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
PJA/src/main/java/com/project/PJA/notification/entity/UserNotification.java
PJA/src/main/java/com/project/PJA/notification/repository/NotificationRepository.java
PJA/src/main/java/com/project/PJA/notification/repository/UserNotificationRepository.java
PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java

closed #63 
- 이벤트 타입 변경
- 액션 위주의 로그 수집

[Refactor] 사용자 행동 로그 리팩토링

---

PJA/src/main/java/com/project/PJA/user/controller/UserController.java
PJA/src/main/java/com/project/PJA/user/dto/SignupDto.java

[Fix] 회원가입 DTO로 인한 에러 해결

---

PJA/src/main/java/com/project/PJA/project_progress/entity/Action.java

[Feature] action의 중요도 최소값 0으로 변경

---

PJA/src/main/java/com/project/PJA/erd/service/ErdService.java

closed #116 
- erd 중복 생성 에러 해결

[Fix] erd 중복 생성 에러 해결

---

PJA/.gitignore
PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

closed #109 
- 아이디어 입력에서 메인 기능과 기술 스택을 삭제할 수 있는 기능 추가했습니다.
- 아이디어 입력에서 메인 기능과 기술 스택이 각각 2개 이상이 아니면 수정되지 않게 했습니다.
- gitignore에 application-*.properties 삭제했습니다.

[Feat] 메인 기능, 기술 스택 삭제 기능 추가

---

PJA/src/main/java/com/project/PJA/erd/entity/ErdTable.java
PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
PJA/src/main/java/com/project/PJA/notification/entity/UserNotification.java
PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureCategoryController.java
PJA/src/main/java/com/project/PJA/project_progress/controller/FeatureController.java
PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java
PJA/src/main/java/com/project/PJA/project_progress/dto/CreateCategoryAndFeatureDto.java
PJA/src/main/java/com/project/PJA/project_progress/dto/FeatureCategoryResponseDto.java
PJA/src/main/java/com/project/PJA/project_progress/dto/FeatureResponseDto.java
PJA/src/main/java/com/project/PJA/project_progress/dto/UpdateActionDto.java
PJA/src/main/java/com/project/PJA/project_progress/dto/UpdateFeatureAndCategoryDto.java
PJA/src/main/java/com/project/PJA/project_progress/entity/Action.java
PJA/src/main/java/com/project/PJA/project_progress/entity/ActionComment.java
PJA/src/main/java/com/project/PJA/project_progress/entity/ActionParticipant.java
PJA/src/main/java/com/project/PJA/project_progress/entity/ActionPost.java
PJA/src/main/java/com/project/PJA/project_progress/entity/ActionPostFile.java
PJA/src/main/java/com/project/PJA/project_progress/entity/Feature.java
PJA/src/main/java/com/project/PJA/project_progress/entity/FeatureCategory.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
PJA/src/main/java/com/project/PJA/project_progress/service/FeatureCategoryService.java
PJA/src/main/java/com/project/PJA/project_progress/service/FeatureService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java

- 프로젝트 진행 관련 삭제 문제 해결
- 카테고리&기능 상태 Boolean으로 변경

[Fix & Refactor] 프로젝트 진행 관련 삭제 문제 해결 및 카테고라&기능 상태 Boolean으로 변경

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
PJA/src/main/java/com/project/PJA/project_progress/repository/FeatureCategoryRepository.java
PJA/src/main/java/com/project/PJA/project_progress/repository/FeatureRepository.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java

- 프로젝트 진행 리스트 순서 Order Index로 변경
- 액션 생성 및 수정 성공 시 data에 actionPostId 추가

[Feat & Refactor] 프로젝트 진행 페이지 관련 기능 수정 및 리팩토링

---

PJA/src/main/java/com/project/PJA/erd/service/ErdService.java

erd ai 생성 요청 에러 해결 (관계도 ai 생성 내용 주석 처리)

[Fix] erd ai 생성 요청 에러 해결

---

PJA/src/main/java/com/project/PJA/user/controller/UserSettingController.java
PJA/src/main/java/com/project/PJA/user/dto/ChangeNameRequestDto.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

[Fix] 사용자 이름 변경에러 해결

---

PJA/src/main/java/com/project/PJA/project_progress/service/FeatureCategoryService.java
PJA/src/main/java/com/project/PJA/project_progress/service/FeatureService.java

[Fix] 카테고리 test 여부 수정 안되는거 수정_ver1

---

PJA/src/main/java/com/project/PJA/git_interlocking/controller/GitInterlockingController.java
PJA/src/main/java/com/project/PJA/git_interlocking/dto/GitInfoDto.java
PJA/src/main/java/com/project/PJA/git_interlocking/entity/GitInterlocking.java
PJA/src/main/java/com/project/PJA/git_interlocking/repository/GitInterlockingRepository.java
PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java

[Feat] 깃 연동 기능 추가

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

[Fix] action ai 추천받기 반환값 수정

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionController.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

action ai 추천받기 PathVariable 값 수정

[Fix] action ai 추천받기 PathVariable 값 수정

---

PJA/src/main/java/com/project/PJA/erd/service/ErdService.java

[Fix] erd id 두 번 생성 에러 수정

---

PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java

closed #138 
요구사항 명세서 AI 추천 시, 기능 요구사항과 성능 요구사항이 각각 3개 이상일 경우에만 신청할 수 있도록 조건을 추가하였습니다. 또한, AI 추천은 워크스페이스의 진행 단계가 요구사항 작성 단계(ZERO, ONE)일 경우에만 가능하도록 검증 로직을 추가하였습니다.

[Feat] AI 추천 조건에 단계 및 요구사항 개수 제한 추가

---

PJA/src/main/java/com/project/PJA/erd/service/ErdService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

[Fix] erd모델 수정

---

PJA/src/main/java/com/project/PJA/erd/repository/ErdColumnRepository.java
PJA/src/main/java/com/project/PJA/erd/service/ErdService.java

[Feat] erd ai 생성 관계도 db에 넣기 추가

---

PJA/src/main/java/com/project/PJA/project_progress/entity/Progress.java

[Feat] 프로젝트 진행 액션 상태 종류 추가

---

PJA/src/main/java/com/project/PJA/api/controller/ApiController.java
PJA/src/main/java/com/project/PJA/api/service/ApiService.java
PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
PJA/src/main/java/com/project/PJA/ideainput/controller/IdeaInputController.java
PJA/src/main/java/com/project/PJA/ideainput/service/IdeaInputService.java
PJA/src/main/java/com/project/PJA/invitation/controller/InvitationController.java
PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java
PJA/src/main/java/com/project/PJA/member/controller/MemberController.java
PJA/src/main/java/com/project/PJA/member/service/MemberService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
PJA/src/main/java/com/project/PJA/projectinfo/controller/ProjectInfoController.java
PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
PJA/src/main/java/com/project/PJA/requirement/controller/RequirementController.java
PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java
PJA/src/main/java/com/project/PJA/workspace_activity/controller/WorkspaceActivityController.java
PJA/src/main/java/com/project/PJA/workspace_activity/dto/WorkspaceActivityResponseDto.java
PJA/src/main/java/com/project/PJA/workspace_activity/entity/WorkspaceActivity.java
PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityActionType.java
PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityTargetType.java
PJA/src/main/java/com/project/PJA/workspace_activity/repository/WorkspaceActivityRepository.java
PJA/src/main/java/com/project/PJA/workspace_activity/service/WorkspaceActivityService.java

[Feature] 최근 활동 기능 개발

---

PJA/src/main/java/com/project/PJA/requirement/service/RequirementService.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

closed #155 
- 요구사항 명세서 항목에 대해 공백 또는 빈 문자열 입력 방지를 위한 유효성 검사 추가
- AI 요구사항 추천 기능에서 워크스페이스 진행 단계(ProgressStep)에 따라 요청 제한 로직 추가
- 아이디어 입력 이전(ZERO) 단계일 경우: "아이디어 입력을 먼저 해주세요"
- 요구사항 작성 이후 단계일 경우: "요구사항 작성 단계가 지난 워크스페이스입니다. AI 추천을 받을 수 없습니다."

[Feat] 요구사항 명세서 AI 추천 요청시 글 길이 유효성 검사 로직 추가

---

PJA/src/main/java/com/project/PJA/notification/controller/NotificationController.java
PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
PJA/src/main/java/com/project/PJA/notification/entity/Notification.java
PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
PJA/src/main/java/com/project/PJA/sse/repository/SseEmitterRepository.java

[Feat] SSE 기능 추가

---

PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

[Refactor] sse 컨트롤러 반환값 수정

---

PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

[Refactor] sse 연결 반환 타입 원래대로 수정

---

PJA/src/main/java/com/project/PJA/actionAnalysis/controller/ActionAnalysisController.java
PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AvgProcessingTimeGraphDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceGraphDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/entity/AvgProcessingTimeResult.java
PJA/src/main/java/com/project/PJA/actionAnalysis/entity/TaskImbalanceResult.java
PJA/src/main/java/com/project/PJA/actionAnalysis/repository/AvgProcessingTimeResultRepository.java
PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java
PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisSaveService.java
PJA/src/main/java/com/project/PJA/user_act_log/dto/UserActionLogParsing.java
PJA/src/main/java/com/project/PJA/user_act_log/service/LogSchedular.java
PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
PJA/src/main/java/com/project/PJA/user_act_log/service/UserActionLogService.java

closed #150 
- 담당자 불균형 분석 그래프 관련 기능 개발
- 중요도에 따른 평균 작업 처리 시간 그래프 관련 기능 개발

[Feat] 대시보드 통계 기능 개발

---

PJA/src/main/java/com/project/PJA/member/dto/MemberResponse.java
PJA/src/main/java/com/project/PJA/member/service/MemberService.java

closed #166 
workspaceMember에 profile 추가

[Feat] workspaceMember에 profile 추가

---

PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

sse 알림 구독 토큰 직접 받아서 user 정보 가져오게 수정

[Feat] sse 알림 구독 토큰 직접 받아서 user 정보 가져오게 수정

---

PJA/src/main/java/com/project/PJA/common/config/WebConfig.java

[Chore] 모든 메서드 허용하도록 수정

---

PJA/src/main/java/com/project/PJA/common/config/WebConfig.java

[Refactor] 오류 수정

---

PJA/src/main/java/com/project/PJA/git_interlocking/controller/GitInterlockingController.java
PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
PJA/src/main/java/com/project/PJA/workspace/entity/Workspace.java

[Feat] 깃허브 url 조회 기능 수정

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
PJA/src/main/java/com/project/PJA/project_progress/dto/MyActionDto.java
PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

[Feat] 진행중인 내 작업(action) 조회하기 기능 추가

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ProjectProgressController.java
PJA/src/main/java/com/project/PJA/project_progress/dto/MyActionDto.java
PJA/src/main/java/com/project/PJA/project_progress/repository/ActionRepository.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

- 내 진행률 불러오기 기능 추가
- 현재 진행중인 작업 리스트 불러오기 수정

[Feat] 내 진행률 불러오기 기능 추가 및 현재 진행중인 작업 리스트 불러오기 수정

---

PJA/src/main/java/com/project/PJA/erd/controller/ErdColumnController.java
PJA/src/main/java/com/project/PJA/erd/controller/ErdTableController.java
PJA/src/main/java/com/project/PJA/erd/dto/ErdColumnResponseDto.java
PJA/src/main/java/com/project/PJA/erd/dto/ErdTableResponseDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/FieldDto.java
PJA/src/main/java/com/project/PJA/erd/dto/reactFlowtDto/TableNodeDto.java
PJA/src/main/java/com/project/PJA/erd/entity/ErdTable.java
PJA/src/main/java/com/project/PJA/erd/service/ErdColumnService.java
PJA/src/main/java/com/project/PJA/erd/service/ErdRelationService.java
PJA/src/main/java/com/project/PJA/erd/service/ErdTableService.java
PJA/src/main/java/com/project/PJA/erd/service/ReactFlowConverter.java

erd ai 생성, 조회, 테이블, 컬럼 관련 리팩토링

[Refactor] erd ai 생성, 조회, 테이블, 컬럼 관련 리팩토링

---

PJA/src/main/java/com/project/PJA/erd/controller/ErdRelationController.java
PJA/src/main/java/com/project/PJA/erd/dto/CreateErdRelationDto.java
PJA/src/main/java/com/project/PJA/erd/dto/ErdRelationResponseDto.java
PJA/src/main/java/com/project/PJA/erd/service/ErdRelationService.java

closed #171 
erd relationships 리팩토링

[Refactor] erd relationships 리팩토링

---

PJA/src/main/java/com/project/PJA/common/config/WebConfig.java
PJA/src/main/java/com/project/PJA/user_act_log/dto/DetailsParticipants.java

[Fix] json 파싱 시 이름 매칭 문제 해결

---

PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceGraphDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java

담당자 불균형 그래프 응답 데이터에 memberId, username 추가

[Refactor] 담당자 불균형 그래프 응답 데이터 추가

---

PJA/src/main/java/com/project/PJA/api/service/ApiService.java
PJA/src/main/java/com/project/PJA/git_interlocking/service/GitInterlockingService.java
PJA/src/main/java/com/project/PJA/workspace_activity/dto/WorkspaceActivityResponseDto.java
PJA/src/main/java/com/project/PJA/workspace_activity/entity/WorkspaceActivity.java
PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityActionType.java
PJA/src/main/java/com/project/PJA/workspace_activity/enumeration/ActivityTargetType.java
PJA/src/main/java/com/project/PJA/workspace_activity/service/WorkspaceActivityService.java

closed #136  
워크스페이스 내의 최근활동 조회 기능 추가

[Feat] 워크스페이스 내의 최근활동 조회 기능 추가

---

PJA/src/main/java/com/project/PJA/user/service/UserService.java

회원 탈퇴 시 이메일 nullable로 인한 문제 해결

[Fix] 회원 탈퇴 시 이메일 nullable로 인한 문제 해결

---

PJA/src/main/java/com/project/PJA/api/service/ApiService.java

closed #157 
API AI 자동 생성 요청 시, 워크스페이스 진행도를 파악해서 진행도가 3이 아니면 오류를 던지게 만들었습니다.

[Feat]  API 명세서 AI 자동 생성 워크스페이스 진행도 검사 로직 추가

---

PJA/src/main/resources/application.properties

[Fix] s3 bucket 이름 잘못된거 수정

---

PJA/src/main/java/com/project/PJA/common/service/S3Service.java

[Refactor] PutObjectRequest에서 .acl() 제거

---

PJA/src/main/java/com/project/PJA/user/service/UserService.java

[Refactor] 프로필 이미지 변경에 save 추가

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java
PJA/src/main/java/com/project/PJA/user/service/UserService.java

프로필 이미지 삭제 및 액션 포스트 파일 업데이트 추가

[Feat] 프로필 이미지 삭제 및 액션 포스트 파일 업데이트 추가

---

PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AvgProcessingTimeGraphDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java

closed #199 
평균 작업 처리 시간 반환 데이터 수정

[Refactor] 평균 작업 처리 시간 반환 데이터 수정

---

PJA/src/main/java/com/project/PJA/projectinfo/dto/PublicProjectInfoResponse.java
PJA/src/main/java/com/project/PJA/projectinfo/service/ProjectInfoService.java
PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceIds.java
PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceRequest.java
PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceResponse.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

closed #204 
유사한 워크스페이스 검색 기능 구현했습니다.

[Feat] 유사한 워크스페이스 검색 기능 추가

---

PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

[Chore] SSE 구독 api 진입 확인을 위한 로그 찍기

---

PJA/src/main/java/com/project/PJA/security/config/SecurityConfig.java

security에서 sse 구독 api는 인증 없이 접근 가능하게 허용 경로 수정

[Chore] security에서 sse 구독 api는 인증 없이 접근 가능하게 허용 경로 수정

---

PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/dto/SimilarWorkspaceIds.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

- 유사한 워크스페이스 검색 http method를 post에서 get으로 수정
- 워크스페이스 아이디에서 프로젝트 아이디로 이름 수정

[Refactor] 유사한 워크스페이스 post에서 get으로 수정, 워크스페이스 아이디에서 프로젝트 아이디로 이름 수정

---

PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

[Feat] 토큰에서 userId 추출 -> uid 추출

---

PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
PJA/src/main/resources/application.properties

[Fix] 커넥션 풀 사이즈 문제 관련 설정

---

PJA/src/main/java/com/project/PJA/common/config/WebConfig.java

[Chore] webconfig에 프론트 도메인 추가

---

PJA/src/main/java/com/project/PJA/project_progress/service/ProjectProgressService.java

closed #219 
프로젝트 진행 초반 AI 생성 내용 DB에 저장

[Feat] 프로젝트 진행 초반 AI 생성 내용 DB에 저장

---

PJA/src/main/java/com/project/PJA/invitation/service/InvitationService.java

closed #220 
초대 메일 url이 localhost:5173으로 되어있어서 www.pja.kr로 수정했습니다.

[Refactor] 초대 이메일 링크 수정

---

PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

createActionDto 수정으로 인했던 에러 해결_ver2

[Fix] createActionDto 수정으로 인했던 에러 해결_ver2

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

[Fix] 액션 생성 시 프론트에서 넘겨주지 않는 값 처리

---

PJA/src/main/java/com/project/PJA/workspace/controller/WorkspaceController.java
PJA/src/main/java/com/project/PJA/workspace/dto/WorkspaceRoleResponse.java
PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

closed #230 
- 워크스페이스 내 사용자 역할을 Redis 캐시에서 조회하는 기능 구현
- 캐시가 없을 경우 캐시 생성 후 재조회하도록 처리
- JSON 파싱 예외 처리 및 로그 추가
- 멤버가 아닐 경우 null 반환

[Feat] 워크스페이스 내 사용자 역할 조회

---

PJA/src/main/java/com/project/PJA/common/service/FlexibleLocalDateTimeDeserializer.java
PJA/src/main/java/com/project/PJA/project_progress/dto/CreateActionDto.java

[Feat] LocalDateTime 커스텀 파서 추가 및 적용

---

PJA/src/main/java/com/project/PJA/actionAnalysis/controller/ActionAnalysisController.java
PJA/src/main/java/com/project/PJA/actionAnalysis/dto/AssigneeDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/dto/TaskImbalanceResponseDto.java
PJA/src/main/java/com/project/PJA/actionAnalysis/repository/TaskImbalanceResultRepository.java
PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisQueryService.java

작업 불균형 그래프 방금 유저 행동 발생한 사람들에 대해서만 담당자 뜨는 문제 고침

[Fix] 작업 불균형 그래프 방금 유저 행동 발생한 사람들에 대해서만 담당자 뜨는 문제 고침

---

PJA/src/main/java/com/project/PJA/actionAnalysis/service/ActionAnalysisSaveService.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java
PJA/src/main/java/com/project/PJA/user_act_log/service/UserActionLogService.java

[Fix] 로그 일단 다 막아서 해결

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java
PJA/src/main/java/com/project/PJA/user_act_log/enumeration/UserActionType.java
PJA/src/main/java/com/project/PJA/user_act_log/service/LogSenderService.java

[Feat] 통계 모델 수정된 버전에 맞춰서 로그 다시 찍기

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java

액션 게시글 댓글 생성 시의 data에 commentId 추가

[Feat] 액션 게시글 댓글 생성 시의 data에 commentId 추가

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java

[Fix] content null 허용하기

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java

[Fix] 기존 파일 삭제하게 했던거 복구

---

PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/sse/controller/SseController.java

SSE 구독 시 커넥션 누수 방지 및 emitter 비동기 처리

[Fix] SSE 구독 시 커넥션 누수 방지 및 emitter 비동기 처리

---

PJA/src/main/java/com/project/PJA/PjaApplication.java
PJA/src/main/java/com/project/PJA/notification/service/NotiAsyncService.java
PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
PJA/src/main/java/com/project/PJA/sse/service/SendEmitterService.java

[Fix] 비동기 메서드 다른 클래스로 분리

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionService.java

action 생성 시 startDate, endDate 빈 문자열 처리

[Fix] action 생성 시 startDate, endDate 빈 문자열 처리

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java

액션 포스트 파일 기존에 있던 파일 삭제되는 문제 해결

[Fix] 액션 포스트 파일 기존에 있던 파일 삭제되는 문제 해결

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java

[Fix] 삭제할 파일 타입 변경

---

PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java

[Feat] 알림 받을 사람에 자기 자신 필터링

---

PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java
PJA/src/main/java/com/project/PJA/project_progress/controller/ActionCommentController.java
PJA/src/main/java/com/project/PJA/project_progress/dto/NotiFacadeDto.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionCommentService.java
PJA/src/main/java/com/project/PJA/project_progress/service/NotificationFacade.java

@Transactional이 붙은 서비스와 비동기 sse 서비스 분리

[Fix] @Transactional이 붙은 서비스와 비동기 sse 서비스 분리

---

PJA/src/main/java/com/project/PJA/security/jwt/JwtTokenProvider.java
PJA/src/main/java/com/project/PJA/security/service/AuthUserService.java
PJA/src/main/java/com/project/PJA/sse/controller/SseController.java
PJA/src/main/java/com/project/PJA/user/repository/UserRepository.java

- sse 인증구조 직접 token에서 userId 가져오는 방식으로 개선

[Fix] sse 인증구조 직접 token에서 userId 가져오는 방식으로 개선

---

PJA/src/main/java/com/project/PJA/notification/dto/NotiReadResponseDto.java
PJA/src/main/java/com/project/PJA/notification/service/NotificationService.java

알림 조회 시(getNotificationNotRead) actionId 추가

[Feat] 알림 조회 시 actionId 추가

---

PJA/src/main/java/com/project/PJA/project_progress/controller/ActionPostController.java
PJA/src/main/java/com/project/PJA/project_progress/dto/ActionCommentResponseDto.java
PJA/src/main/java/com/project/PJA/project_progress/service/ActionPostService.java

- actionPost 게시글 조회의 commentList에 author 여부값 추가

[Feat] actionPost 게시글 조회의 commentList에 author 여부값 추가

---

PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java

[Fix] erd 생성이랑 erd ai 생성 컨트롤러 합치기

---

PJA/src/main/java/com/project/PJA/erd/controller/ErdController.java
PJA/src/main/java/com/project/PJA/erd/service/ErdService.java

closed #329 
- erd ai 생성 요청 코드 리팩토링

[Refactor] erd ai 생성 요청 코드 리팩토링

---

PJA/src/main/java/com/project/PJA/security/service/RefreshTokenService.java

[Fix] refresh token redis key이름 변경

---

PJA/src/main/java/com/project/PJA/workspace/service/WorkspaceService.java

closed #332 
- 유사한 워크스페이스 검색 권한 로직 수정
- 기존에는 오너 및 멤버만 검색 가능했으나, 공개 워크스페이스는 모든 사용자에게 검색 가능, 비공개 워크스페이스는 해당 팀원에게만 검색 가능하도록 변경
- Redis 기반 권한 검사 로직 개선
- validateWorkspaceAccessFromCache에서 ForbiddenException이 RuntimeException으로 덮이는 문제 수정
- 예외 분기 처리를 통해 적절한 403 응답이 반환되도록 개선

[Feat] 유사 워크스페이스 검색 권한 로직 수정
